# Generated by Django 4.0.10 on 2023-06-29 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=11)),
                ('telefono_movil', models.CharField(blank=True, default='', max_length=30)),
                ('telefono_fijo', models.CharField(blank=True, default='', max_length=30)),
                ('notas', models.CharField(blank=True, default='', max_length=250)),
                ('direcciones', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(default='', max_length=250)),
                ('ciudad', models.CharField(choices=[('VDM', 'Viña del Mar'), ('STGO', 'Santiago'), ('ETC', 'Etcétera')], default='VDM', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField(default=1)),
                ('sku', models.CharField(max_length=15)),
                ('stock', models.IntegerField(default=0)),
                ('modelo', models.CharField(default=None, max_length=250)),
                ('impuesto', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaccion', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('suma_descuentos', models.FloatField(default=0)),
                ('total_pedido', models.FloatField(default=0)),
                ('fecha_pedido', models.DateTimeField(default='2023-1-1')),
                ('direccion', models.CharField(default='', max_length=250)),
                ('cliente_solicitante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.cliente')),
                ('productos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.producto')),
            ],
        ),
    ]
