# Generated by Django 4.2.2 on 2023-07-10 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('nombres', models.CharField(blank=True, default='', max_length=15)),
                ('apellidos', models.CharField(blank=True, default='', max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, default='', max_length=15)),
                ('telefono_movil', models.CharField(blank=True, default='', max_length=30)),
                ('notas', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=250)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compraventa.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(default='', max_length=250)),
                ('ciudad', models.CharField(choices=[('VDM', 'Viña del Mar'), ('STGO', 'Santiago'), ('ETC', 'Etcétera')], default='VDM', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=256, null=True)),
                ('precio', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=0)),
                ('modelo', models.CharField(default=None, max_length=250)),
                ('descuento', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now=True, null=True)),
                ('tiene_despacho', models.BooleanField(null=True)),
                ('estado_despacho', models.CharField(choices=[('Recibido', 'Recibido'), ('Pago aceptado', 'Pago aceptado'), ('Orden de compra generada', 'Orden de compra generada'), ('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('En transito', 'En transito'), ('Entregado', 'Entregado')], default='Recibido', max_length=30, null=True)),
                ('impuesto', models.IntegerField(default=19)),
                ('cliente_solicitante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.cliente')),
                ('direccion_despacho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itempedido_set', to='compraventa.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.producto')),
            ],
        ),
    ]
