# Generated by Django 4.2.2 on 2023-07-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_despacho',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('Pago aceptado', 'Pago aceptado'), ('Orden de compra generada', 'Orden de compra generada'), ('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('En transito', 'En transito'), ('Entregado', 'Entregado'), ('Cancelacion solicitada', 'Cancelacion solicitada'), ('Cancelado', 'Cancelado')], default='Recibido', max_length=30, null=True),
        ),
    ]
