# Generated by Django 4.2.2 on 2023-07-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0002_alter_pedido_estado_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tiene_despacho',
            field=models.BooleanField(default=True),
        ),
    ]
