# Generated by Django 4.2.2 on 2023-07-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0002_remove_pedido_numero_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
