# Generated by Django 4.2.2 on 2023-06-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0002_categoria_cliente_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_solicitante',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_solicitante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.cliente'),
        ),
    ]
