# Generated by Django 4.2.2 on 2023-06-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0003_remove_pedido_cliente_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.TextField(default=None, max_length=250),
        ),
    ]
