# Generated by Django 4.2.2 on 2023-07-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0006_alter_pedido_id_pedido_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_solicitante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='compraventa.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
