# Generated by Django 4.2.2 on 2023-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0006_remove_producto_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direcciones',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_movil',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
